export const AppointmentFormActionTypes = {
  SET_PATIENT_NAME: 'SET_PATIENT_NAME',
  SET_SELECTED_DATE: 'SET_SELECTED_DATE',
  SET_SELECTED_TIME: 'SET_SELECTED_TIME',
  SET_DESCRIPTION: 'SET_DESCRIPTION',
  RESET_FORM: 'RESET_FORM',
} as const;
